package nazar.oop.application;

import nazar.oop.data.LoginRequest;

public class RecordApp {
    public static void main(String[] args) {
        System.out.println("Demo Record class, Record tidak bisa extends, hanya bisa implements");
        LoginRequest loginRequest = new LoginRequest("nazar", "permana");
        System.out.println(loginRequest.username());
        System.out.println(loginRequest.password());
        System.out.println(loginRequest);   // toString() method already generated by Java


        System.out.println(new LoginRequest());
        System.out.println(new LoginRequest("nazar"));
        System.out.println(new LoginRequest("nazar", "rahasia"));

        loginRequest.greetings();
    }
}
